[iOS] RTCAudioSession のロックについて説明を書く
shiguredo-webrtc-build/webrtc-build pull request #19
Opened 2021-04-20 07:59 UTC by szktty

ロックの競合の修正内容のコメントの補足説明を書きました。

2021-04-21 01:29 UTC, enm10k approved these changes
ありがとうございました!
1点気になった箇所にコメントをしているので、検討していただければと思います

2021-04-21 01:29 UTC, enm10k commented on docs/patch_ios.md
> +どこかですでにロックされている状態で上記のコードが実行されるとデッドロックしてしまう。
> どこかですでにロックされている状態 ...

一般的に、複数スレッドからアクセスされる場合は、既にロックされていてもデッドロックは発生しないと思うので、 `同一スレッド` というキーワードを使った表現に書き直してはどうかと思いました

2021-04-21 02:09 UTC, melpon commented
LGTM です。

2021-04-27 06:44 UTC, szktty commented on docs/patch_ios.md
> +どこかですでにロックされている状態で上記のコードが実行されるとデッドロックしてしまう。
@enm10k RTCAudioSession のロックについてもう少し詳しく書きました。
https://github.com/shiguredo-webrtc-build/webrtc-build/pull/19/commits/092333c7aaedd8682f011a25a50e4cb22aa39014

2021-05-26 10:33 UTC, voluntas commented
@enm10k これ見ておいてもらえる？問題なければマージしたいです。

2021-05-26 10:41 UTC, enm10k requested changes

2021-05-26 10:41 UTC, enm10k commented on docs/patch_ios.md
> +`RTCAudioSession` の相互排他ロックは同一スレッド間のみに制限されないので注意すべき。
@szktty 
> `RTCAudioSession` の相互排他ロックは同一スレッド間のみに制限されないので注意すべき。

こちら、別スレッドからロックを取得、開放するコードを書いて実験した際はデッドロックが発生しなかったと思うので、修正していただければと思います。

2021-06-23 01:26 UTC, voluntas commented on docs/patch_ios.md
> +`RTCAudioSession` の相互排他ロックは同一スレッド間のみに制限されないので注意すべき。
@szktty こちら見ておいていただけると。

2021-06-23 05:51 UTC, szktty commented on docs/patch_ios.md
> +`RTCAudioSession` の相互排他ロックは同一スレッド間のみに制限されないので注意すべき。
@voluntas 途中まで書き直してますが他のタスクで後回しになってます。一段落したら再開します。

2021-07-02 09:19 UTC, enm10k approved these changes

2021-07-02 09:20 UTC, enm10k commented
@szktty 
修正を確認しました
ありがとうございました

2021-07-02 09:22 UTC, merged