Feature/patch docs ios android
shiguredo-webrtc-build/webrtc-build pull request #39
Opened 2022-03-08 07:31 UTC by szktty

iOS / Android のパッチの説明を追記します。

2022-03-09 02:19 UTC, enm10k commented on patches/README.md
> +iOS でのマイク不使用時のパーミッション要求を抑制するパッチ。詳細は `docs/patch_ios.md` を参照すること。
iOS 向けのパッチが増えてきたので、 https://github.com/shiguredo-webrtc-build/webrtc-build/blame/master/docs/patch_ios.md#L1 を修正して、 `ios_manual_audio_input.patch` の詳細が説明されていることを表現できると良いのではないかと思いました

2022-03-09 02:22 UTC, enm10k commented on patches/README.md
> +**先の `-gdwarf-aranges` フラグ周りの問題は既に本家に取り込まれたため削除した。**
この行は削除しても良いのではないかと思いました

2022-03-09 02:29 UTC, enm10k requested changes
細かいですが、2点ほどコメントしました

対応よろしくお願いいたします

2022-03-14 06:47 UTC, szktty commented on patches/README.md
> +iOS でのマイク不使用時のパーミッション要求を抑制するパッチ。詳細は `docs/patch_ios.md` を参照すること。
@enm10k 修正しました。ファイル名を変更しました。
https://github.com/shiguredo-webrtc-build/webrtc-build/commit/7f0b5c2e6a5e15c0d1c85f7344c5ec201fe52c12
https://github.com/shiguredo-webrtc-build/webrtc-build/commit/c6fd73df31bfd69e5801ca2157c119929d817820

2022-03-14 06:54 UTC, szktty commented on patches/README.md
> +**先の `-gdwarf-aranges` フラグ周りの問題は既に本家に取り込まれたため削除した。**
@enm10k ファイルは残っていますが使われなくなったパッチなので、この記述を消すと混乱を招きそうです。

2022-03-23 01:34 UTC, enm10k commented on patches/README.md
> +**先の `-gdwarf-aranges` フラグ周りの問題は既に本家に取り込まれたため削除した。**
@szktty 
どのようなケースで混乱が生じるのか理解できていないので、説明していただけませんでしょうか?

`-gdwarf-aranges` フラグ周りの問題に関する説明がないので、 `先の 〜` と言われてもこれを読む人は理解できないのではないかと思っています
なので、私はこちらの行を削除しても良いのではないかと考えました

(`-gdwarf-aranges` フラグ周りの問題については、 run.py のコメントで一部説明されている箇所がありますね)

2022-03-23 05:34 UTC, szktty commented on patches/README.md
> +**先の `-gdwarf-aranges` フラグ周りの問題は既に本家に取り込まれたため削除した。**
@enm10k https://github.com/shiguredo-webrtc-build/webrtc-build/commit/4b087a9196514b47da340b0fc410ab0aa97cdb1f
フラグの説明に関する指摘とのことで、確かにここで説明する必要はないので削除しました。パッチが削除されたと↑で書いたのは私の勘違いです。

2022-03-23 06:00 UTC, enm10k commented on patches/README.md
> +**先の `-gdwarf-aranges` フラグ周りの問題は既に本家に取り込まれたため削除した。**
対応ありがとうございます

2022-03-23 06:01 UTC, enm10k approved these changes

2022-03-23 06:47 UTC, miosakuma approved these changes

2022-03-23 06:51 UTC, merged